#!/bin/bash
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

# Path to the JSON file
config_file="../config.json"

# Read values from JSON file using jq
IP_ADDRESS=$(jq -r '.serverIpAddress' "$config_file")

# Generate a new RSA key/cert for local development
HOST=$IP_ADDRESS
CRT="$HOST.crt"
KEY="$HOST.key"

# Install the system certificate if it's not already
# NOTE: The ecdsa flag does nothing but I wish it did
go run filippo.io/mkcert -ecdsa -install

# Generate a new certificate for host
# This fork of mkcert supports the -days flag.
# TODO remove the -days flag when Chrome accepts self-signed certs.
go run filippo.io/mkcert -ecdsa -days 10 -cert-file "$CRT" -key-file "$KEY" $IP_ADDRESS 127.0.0.1 ::1
