#!/bin/bash
set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")/.."

# Generate the self-signed certificate if needed
./dev/cert

# Use debug logging by default
export RUST_LOG="${RUST_LOG:-debug}"

# Path to the JSON file
config_file="config.json"

# Read values from JSON file using jq
IP_ADDRESS=$(jq -r '.serverIpAddress' "$config_file")
SERVER_PORT=$(jq -r '.serverPort' "$config_file")

# Default to a self-signed certificate
# TODO automatically generate if it doesn't exist.
CERT="${CERT:-dev/$IP_ADDRESS.crt}"
KEY="${KEY:-dev/$IP_ADDRESS.key}"

# Default to listening on localhost:4443
PORT="${PORT:-$SERVER_PORT}"
BIND="${BIND:-[::]:$PORT}"

# A list of optional args
ARGS=""

# Connect to the given URL to get announcements
# TODO default to a public instance?
if [ -n "${ANNOUNCE-}" ]; then
	ARGS="$ARGS --announce $ANNOUNCE"
fi

# Provide our node URL when registering origins.
if [ -n "${HOST-}" ]; then
	ARGS="$ARGS --host $HOST"
fi

echo "Publish URL: https://quic.video/publish/?server=$IP_ADDRESS:$PORT"

# Run the relay and forward any arguments
cargo run --bin moq-relay -- --bind "$BIND" --tls-cert "$CERT" --tls-key "$KEY" --dev $ARGS -- "$@"
